// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvhywacjcwcsklyciabo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2aHl3YWNqY3djc2tseWNpYWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NTk4MzksImV4cCI6MjA2MjMzNTgzOX0.87Od0kIRffCdrqPP5WHIX0CBwfIzzX8usnD9aVSSu8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);